{{/*
Copyright 2026 Google LLC
Licensed under the Apache License, Version 2.0. See LICENSE for details.
*/}}
{{- if .Values.watcher.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mast.watcherSA" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: k8s-event-watcher
    {{- include "mast.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "mast.watcherSA" . }}
  labels:
    app.kubernetes.io/name: k8s-event-watcher
    {{- include "mast.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "mast.watcherSA" . }}
  labels:
    app.kubernetes.io/name: k8s-event-watcher
    {{- include "mast.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "mast.watcherSA" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "mast.watcherSA" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
