{{/*
Copyright 2026 Google LLC
Licensed under the Apache License, Version 2.0. See LICENSE for details.
*/}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mast.daemonName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: mast
    {{- include "mast.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mast
    app.kubernetes.io/component: daemon
  ports:
    - name: inject
      port: 7777
      targetPort: inject
      protocol: TCP
