# Copyright 2026 Google LLC
# Licensed under the Apache License, Version 2.0. See LICENSE for details.
#
# Originally derived from
# go-steer/core-agent@c5efbb9e:examples/gke-troubleshoot-agent/deploy/base/11-serviceaccount-watcher.yaml.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-event-watcher
  namespace: mast-triage
  labels:
    app.kubernetes.io/name: k8s-event-watcher
