// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by dev/regen-builtin-pricing. DO NOT EDIT.
//
// Regenerated 2026-09-03 from https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json.
//
// To refresh: `go run ./dev/regen-builtin-pricing`
//
// Membership is a rule, not a list: every Gemini and Anthropic model
// in LiteLLM's catalog that is mode="chat", supports function calling,
// carries a published price and window, and is not deprecated. See
// eligible() in dev/regen-builtin-pricing/main.go — adjust the rule
// there, never this file.
//
// Three tables, one pass: bare-id rates, (backend, model) rates, and
// context windows. The second exists because a rate belongs to the
// backend that served the tokens, not to the model id — see
// builtinByBackend's own comment.
//
// Issue #259 context: this file used to be hand-authored, drifted
// silently, and shipped rates that were off by 20-30x during the
// v2.7.0-dev.3 demo drive. The regen path is the mitigation — every
// entry carries an UpdatedAt so operators can spot stale entries via
// /pricing, and the whole file rebuilds from LiteLLM's authoritative
// catalog rather than accreting hand-edits.

package pricing

import "time"

var builtin = map[string]Rates{
	"claude-fable-5":                        {InputPerMTok: 10, CachedInputPerMTok: 1, CacheCreationInputPerMTok: 12.5, OutputPerMTok: 50, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},    // anthropic
	"claude-fable-5-1":                      {InputPerMTok: 10, CachedInputPerMTok: 0.25, CacheCreationInputPerMTok: 12.5, OutputPerMTok: 50, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)}, // anthropic
	"claude-haiku-4-5":                      {InputPerMTok: 1, CachedInputPerMTok: 0.1, CacheCreationInputPerMTok: 1.25, OutputPerMTok: 5, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},    // anthropic
	"claude-haiku-4-5-20251001":             {InputPerMTok: 1, CachedInputPerMTok: 0.1, CacheCreationInputPerMTok: 1.25, OutputPerMTok: 5, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},    // anthropic
	"claude-mythos-5":                       {InputPerMTok: 10, CachedInputPerMTok: 1, CacheCreationInputPerMTok: 12.5, OutputPerMTok: 50, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},    // anthropic
	"claude-mythos-preview":                 {InputPerMTok: 10, CachedInputPerMTok: 1, CacheCreationInputPerMTok: 12.5, OutputPerMTok: 50, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},    // anthropic
	"claude-opus-4-5":                       {InputPerMTok: 5, CachedInputPerMTok: 0.5, CacheCreationInputPerMTok: 6.25, OutputPerMTok: 25, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},   // anthropic
	"claude-opus-4-5-20251101":              {InputPerMTok: 5, CachedInputPerMTok: 0.5, CacheCreationInputPerMTok: 6.25, OutputPerMTok: 25, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},   // anthropic
	"claude-opus-4-6":                       {InputPerMTok: 5, CachedInputPerMTok: 0.5, CacheCreationInputPerMTok: 6.25, OutputPerMTok: 25, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},   // anthropic
	"claude-opus-4-6-20260205":              {InputPerMTok: 5, CachedInputPerMTok: 0.5, CacheCreationInputPerMTok: 6.25, OutputPerMTok: 25, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},   // anthropic
	"claude-opus-4-7":                       {InputPerMTok: 5, CachedInputPerMTok: 0.5, CacheCreationInputPerMTok: 6.25, OutputPerMTok: 25, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},   // anthropic
	"claude-opus-4-7-20260416":              {InputPerMTok: 5, CachedInputPerMTok: 0.5, CacheCreationInputPerMTok: 6.25, OutputPerMTok: 25, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},   // anthropic
	"claude-opus-4-8":                       {InputPerMTok: 5, CachedInputPerMTok: 0.5, CacheCreationInputPerMTok: 6.25, OutputPerMTok: 25, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},   // anthropic
	"claude-opus-5":                         {InputPerMTok: 5, CachedInputPerMTok: 0.5, CacheCreationInputPerMTok: 6.25, OutputPerMTok: 25, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},   // anthropic
	"claude-sonnet-4-5":                     {InputPerMTok: 3, CachedInputPerMTok: 0.3, CacheCreationInputPerMTok: 3.75, OutputPerMTok: 15, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},   // anthropic
	"claude-sonnet-4-5-20250929":            {InputPerMTok: 3, CachedInputPerMTok: 0.3, CacheCreationInputPerMTok: 3.75, OutputPerMTok: 15, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},   // anthropic
	"claude-sonnet-4-6":                     {InputPerMTok: 3, CachedInputPerMTok: 0.3, CacheCreationInputPerMTok: 3.75, OutputPerMTok: 15, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},   // anthropic
	"claude-sonnet-5":                       {InputPerMTok: 2, CachedInputPerMTok: 0.2, CacheCreationInputPerMTok: 2.5, OutputPerMTok: 10, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},    // anthropic
	"gemini-2.5-flash":                      {InputPerMTok: 0.3, CachedInputPerMTok: 0.03, OutputPerMTok: 2.5, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},                                // vertex_ai-language-models
	"gemini-2.5-flash-lite":                 {InputPerMTok: 0.1, CachedInputPerMTok: 0.01, OutputPerMTok: 0.4, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},                                // vertex_ai-language-models
	"gemini-2.5-flash-lite-preview-09-2025": {InputPerMTok: 0.1, CachedInputPerMTok: 0.01, OutputPerMTok: 0.4, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},                                // vertex_ai-language-models
	"gemini-2.5-flash-preview-09-2025":      {InputPerMTok: 0.3, CachedInputPerMTok: 0.03, OutputPerMTok: 2.5, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},                                // vertex_ai-language-models
	"gemini-2.5-pro":                        {InputPerMTok: 1.25, CachedInputPerMTok: 0.125, OutputPerMTok: 10, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},                               // vertex_ai-language-models
	"gemini-3-flash-preview":                {InputPerMTok: 0.5, CachedInputPerMTok: 0.05, OutputPerMTok: 3, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},                                  // vertex_ai-language-models
	"gemini-3.1-flash-lite":                 {InputPerMTok: 0.25, CachedInputPerMTok: 0.025, OutputPerMTok: 1.5, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},                              // vertex_ai-language-models
	"gemini-3.1-flash-lite-preview":         {InputPerMTok: 0.25, CachedInputPerMTok: 0.025, OutputPerMTok: 1.5, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},                              // vertex_ai-language-models
	"gemini-3.1-pro-preview":                {InputPerMTok: 2, CachedInputPerMTok: 0.2, OutputPerMTok: 12, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},                                    // vertex_ai-language-models
	"gemini-3.1-pro-preview-customtools":    {InputPerMTok: 2, CachedInputPerMTok: 0.2, OutputPerMTok: 12, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},                                    // vertex_ai-language-models
	"gemini-3.5-flash":                      {InputPerMTok: 1.5, CachedInputPerMTok: 0.15, OutputPerMTok: 9, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},                                  // vertex_ai-language-models
	"gemini-3.5-flash-lite":                 {InputPerMTok: 0.3, CachedInputPerMTok: 0.03, OutputPerMTok: 2.5, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},                                // vertex_ai-language-models
	"gemini-3.6-flash":                      {InputPerMTok: 0.75, CachedInputPerMTok: 0.075, OutputPerMTok: 3.75, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},                             // vertex_ai-language-models
	"gemini-3.7-flash":                      {InputPerMTok: 0.75, CachedInputPerMTok: 0.075, OutputPerMTok: 3.75, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},                             // vertex_ai-language-models
}

// builtinByBackend prices the (backend, model) pair rather than the
// model id, under keys of the form "<backend>/<model>". The backend
// names are mast's own — "anthropic", "anthropic-vertex", "gemini",
// "vertex" — so a caller that has resolved which backend will serve a
// call can build the key directly. Read it through LookupFor.
//
// The bare `builtin` table above cannot express this: LiteLLM's
// unprefixed claude-* rates are Anthropic first-party while its
// unprefixed gemini-* rates are Vertex, so the bare table is a mixture
// of two backends that happens to be right only while each family's
// backends charge the same. That is true as of this regen and is not a
// guarantee anyone makes.
//
// Not every pair exists: a model a backend does not serve has no row,
// and LookupFor falls back to the bare id for it.
var builtinByBackend = map[string]Rates{
	"anthropic-vertex/claude-fable-5":              {InputPerMTok: 10, CachedInputPerMTok: 1, CacheCreationInputPerMTok: 12.5, OutputPerMTok: 50, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},    // vertex_ai-anthropic_models
	"anthropic-vertex/claude-fable-5-1":            {InputPerMTok: 10, CachedInputPerMTok: 0.25, CacheCreationInputPerMTok: 12.5, OutputPerMTok: 50, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)}, // vertex_ai-anthropic_models
	"anthropic-vertex/claude-haiku-4-5":            {InputPerMTok: 1, CachedInputPerMTok: 0.1, CacheCreationInputPerMTok: 1.25, OutputPerMTok: 5, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},    // vertex_ai-anthropic_models
	"anthropic-vertex/claude-haiku-4-5-20251001":   {InputPerMTok: 1, CachedInputPerMTok: 0.1, CacheCreationInputPerMTok: 1.25, OutputPerMTok: 5, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},    // vertex_ai-anthropic_models
	"anthropic-vertex/claude-opus-4-5":             {InputPerMTok: 5, CachedInputPerMTok: 0.5, CacheCreationInputPerMTok: 6.25, OutputPerMTok: 25, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},   // vertex_ai-anthropic_models
	"anthropic-vertex/claude-opus-4-5-20251101":    {InputPerMTok: 5, CachedInputPerMTok: 0.5, CacheCreationInputPerMTok: 6.25, OutputPerMTok: 25, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},   // vertex_ai-anthropic_models
	"anthropic-vertex/claude-opus-4-6":             {InputPerMTok: 5, CachedInputPerMTok: 0.5, CacheCreationInputPerMTok: 6.25, OutputPerMTok: 25, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},   // vertex_ai-anthropic_models
	"anthropic-vertex/claude-opus-4-7":             {InputPerMTok: 5, CachedInputPerMTok: 0.5, CacheCreationInputPerMTok: 6.25, OutputPerMTok: 25, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},   // vertex_ai-anthropic_models
	"anthropic-vertex/claude-opus-4-8":             {InputPerMTok: 5, CachedInputPerMTok: 0.5, CacheCreationInputPerMTok: 6.25, OutputPerMTok: 25, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},   // vertex_ai-anthropic_models
	"anthropic-vertex/claude-opus-5":               {InputPerMTok: 5, CachedInputPerMTok: 0.5, CacheCreationInputPerMTok: 6.25, OutputPerMTok: 25, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},   // vertex_ai-anthropic_models
	"anthropic-vertex/claude-sonnet-4-5":           {InputPerMTok: 3, CachedInputPerMTok: 0.3, CacheCreationInputPerMTok: 3.75, OutputPerMTok: 15, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},   // vertex_ai-anthropic_models
	"anthropic-vertex/claude-sonnet-4-5-20250929":  {InputPerMTok: 3, CachedInputPerMTok: 0.3, CacheCreationInputPerMTok: 3.75, OutputPerMTok: 15, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},   // vertex_ai-anthropic_models
	"anthropic-vertex/claude-sonnet-4-6":           {InputPerMTok: 3, CachedInputPerMTok: 0.3, CacheCreationInputPerMTok: 3.75, OutputPerMTok: 15, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},   // vertex_ai-anthropic_models
	"anthropic-vertex/claude-sonnet-5":             {InputPerMTok: 2, CachedInputPerMTok: 0.2, CacheCreationInputPerMTok: 2.5, OutputPerMTok: 10, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},    // vertex_ai-anthropic_models
	"anthropic/claude-fable-5":                     {InputPerMTok: 10, CachedInputPerMTok: 1, CacheCreationInputPerMTok: 12.5, OutputPerMTok: 50, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},    // anthropic
	"anthropic/claude-fable-5-1":                   {InputPerMTok: 10, CachedInputPerMTok: 0.25, CacheCreationInputPerMTok: 12.5, OutputPerMTok: 50, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)}, // anthropic
	"anthropic/claude-haiku-4-5":                   {InputPerMTok: 1, CachedInputPerMTok: 0.1, CacheCreationInputPerMTok: 1.25, OutputPerMTok: 5, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},    // anthropic
	"anthropic/claude-haiku-4-5-20251001":          {InputPerMTok: 1, CachedInputPerMTok: 0.1, CacheCreationInputPerMTok: 1.25, OutputPerMTok: 5, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},    // anthropic
	"anthropic/claude-mythos-5":                    {InputPerMTok: 10, CachedInputPerMTok: 1, CacheCreationInputPerMTok: 12.5, OutputPerMTok: 50, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},    // anthropic
	"anthropic/claude-mythos-preview":              {InputPerMTok: 10, CachedInputPerMTok: 1, CacheCreationInputPerMTok: 12.5, OutputPerMTok: 50, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},    // anthropic
	"anthropic/claude-opus-4-5":                    {InputPerMTok: 5, CachedInputPerMTok: 0.5, CacheCreationInputPerMTok: 6.25, OutputPerMTok: 25, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},   // anthropic
	"anthropic/claude-opus-4-5-20251101":           {InputPerMTok: 5, CachedInputPerMTok: 0.5, CacheCreationInputPerMTok: 6.25, OutputPerMTok: 25, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},   // anthropic
	"anthropic/claude-opus-4-6":                    {InputPerMTok: 5, CachedInputPerMTok: 0.5, CacheCreationInputPerMTok: 6.25, OutputPerMTok: 25, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},   // anthropic
	"anthropic/claude-opus-4-6-20260205":           {InputPerMTok: 5, CachedInputPerMTok: 0.5, CacheCreationInputPerMTok: 6.25, OutputPerMTok: 25, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},   // anthropic
	"anthropic/claude-opus-4-7":                    {InputPerMTok: 5, CachedInputPerMTok: 0.5, CacheCreationInputPerMTok: 6.25, OutputPerMTok: 25, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},   // anthropic
	"anthropic/claude-opus-4-7-20260416":           {InputPerMTok: 5, CachedInputPerMTok: 0.5, CacheCreationInputPerMTok: 6.25, OutputPerMTok: 25, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},   // anthropic
	"anthropic/claude-opus-4-8":                    {InputPerMTok: 5, CachedInputPerMTok: 0.5, CacheCreationInputPerMTok: 6.25, OutputPerMTok: 25, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},   // anthropic
	"anthropic/claude-opus-5":                      {InputPerMTok: 5, CachedInputPerMTok: 0.5, CacheCreationInputPerMTok: 6.25, OutputPerMTok: 25, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},   // anthropic
	"anthropic/claude-sonnet-4-5":                  {InputPerMTok: 3, CachedInputPerMTok: 0.3, CacheCreationInputPerMTok: 3.75, OutputPerMTok: 15, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},   // anthropic
	"anthropic/claude-sonnet-4-5-20250929":         {InputPerMTok: 3, CachedInputPerMTok: 0.3, CacheCreationInputPerMTok: 3.75, OutputPerMTok: 15, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},   // anthropic
	"anthropic/claude-sonnet-4-6":                  {InputPerMTok: 3, CachedInputPerMTok: 0.3, CacheCreationInputPerMTok: 3.75, OutputPerMTok: 15, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},   // anthropic
	"anthropic/claude-sonnet-5":                    {InputPerMTok: 2, CachedInputPerMTok: 0.2, CacheCreationInputPerMTok: 2.5, OutputPerMTok: 10, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},    // anthropic
	"gemini/gemini-2.5-flash":                      {InputPerMTok: 0.3, CachedInputPerMTok: 0.03, OutputPerMTok: 2.5, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},                                // gemini
	"gemini/gemini-2.5-flash-lite":                 {InputPerMTok: 0.1, CachedInputPerMTok: 0.01, OutputPerMTok: 0.4, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},                                // gemini
	"gemini/gemini-2.5-flash-lite-preview-09-2025": {InputPerMTok: 0.1, CachedInputPerMTok: 0.01, OutputPerMTok: 0.4, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},                                // gemini
	"gemini/gemini-2.5-flash-preview-09-2025":      {InputPerMTok: 0.3, CachedInputPerMTok: 0.03, OutputPerMTok: 2.5, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},                                // gemini
	"gemini/gemini-2.5-pro":                        {InputPerMTok: 1.25, CachedInputPerMTok: 0.125, OutputPerMTok: 10, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},                               // gemini
	"gemini/gemini-3-flash-preview":                {InputPerMTok: 0.5, CachedInputPerMTok: 0.05, OutputPerMTok: 3, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},                                  // gemini
	"gemini/gemini-3.1-flash-lite":                 {InputPerMTok: 0.25, CachedInputPerMTok: 0.025, OutputPerMTok: 1.5, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},                              // gemini
	"gemini/gemini-3.1-flash-lite-preview":         {InputPerMTok: 0.25, CachedInputPerMTok: 0.025, OutputPerMTok: 1.5, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},                              // gemini
	"gemini/gemini-3.1-pro-preview":                {InputPerMTok: 2, CachedInputPerMTok: 0.2, OutputPerMTok: 12, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},                                    // gemini
	"gemini/gemini-3.1-pro-preview-customtools":    {InputPerMTok: 2, CachedInputPerMTok: 0.2, OutputPerMTok: 12, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},                                    // gemini
	"gemini/gemini-3.5-flash":                      {InputPerMTok: 1.5, CachedInputPerMTok: 0.15, OutputPerMTok: 9, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},                                  // gemini
	"gemini/gemini-3.5-flash-lite":                 {InputPerMTok: 0.3, CachedInputPerMTok: 0.03, OutputPerMTok: 2.5, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},                                // gemini
	"gemini/gemini-3.6-flash":                      {InputPerMTok: 0.75, CachedInputPerMTok: 0.075, OutputPerMTok: 3.75, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},                             // gemini
	"gemini/gemini-3.7-flash":                      {InputPerMTok: 0.75, CachedInputPerMTok: 0.075, OutputPerMTok: 3.75, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},                             // gemini
	"vertex/gemini-2.5-flash":                      {InputPerMTok: 0.3, CachedInputPerMTok: 0.03, OutputPerMTok: 2.5, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},                                // vertex_ai-language-models
	"vertex/gemini-2.5-flash-lite":                 {InputPerMTok: 0.1, CachedInputPerMTok: 0.01, OutputPerMTok: 0.4, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},                                // vertex_ai-language-models
	"vertex/gemini-2.5-flash-lite-preview-09-2025": {InputPerMTok: 0.1, CachedInputPerMTok: 0.01, OutputPerMTok: 0.4, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},                                // vertex_ai-language-models
	"vertex/gemini-2.5-flash-preview-09-2025":      {InputPerMTok: 0.3, CachedInputPerMTok: 0.03, OutputPerMTok: 2.5, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},                                // vertex_ai-language-models
	"vertex/gemini-2.5-pro":                        {InputPerMTok: 1.25, CachedInputPerMTok: 0.125, OutputPerMTok: 10, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},                               // vertex_ai-language-models
	"vertex/gemini-3-flash-preview":                {InputPerMTok: 0.5, CachedInputPerMTok: 0.05, OutputPerMTok: 3, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},                                  // vertex_ai-language-models
	"vertex/gemini-3.1-flash-lite":                 {InputPerMTok: 0.25, CachedInputPerMTok: 0.025, OutputPerMTok: 1.5, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},                              // vertex_ai-language-models
	"vertex/gemini-3.1-flash-lite-preview":         {InputPerMTok: 0.25, CachedInputPerMTok: 0.025, OutputPerMTok: 1.5, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},                              // vertex_ai-language-models
	"vertex/gemini-3.1-pro-preview":                {InputPerMTok: 2, CachedInputPerMTok: 0.2, OutputPerMTok: 12, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},                                    // vertex_ai-language-models
	"vertex/gemini-3.1-pro-preview-customtools":    {InputPerMTok: 2, CachedInputPerMTok: 0.2, OutputPerMTok: 12, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},                                    // vertex_ai-language-models
	"vertex/gemini-3.5-flash":                      {InputPerMTok: 1.5, CachedInputPerMTok: 0.15, OutputPerMTok: 9, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},                                  // vertex_ai-language-models
	"vertex/gemini-3.5-flash-lite":                 {InputPerMTok: 0.3, CachedInputPerMTok: 0.03, OutputPerMTok: 2.5, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},                                // vertex_ai-language-models
	"vertex/gemini-3.6-flash":                      {InputPerMTok: 0.75, CachedInputPerMTok: 0.075, OutputPerMTok: 3.75, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},                             // vertex_ai-language-models
	"vertex/gemini-3.7-flash":                      {InputPerMTok: 0.75, CachedInputPerMTok: 0.075, OutputPerMTok: 3.75, UpdatedAt: time.Date(2026, 9, 3, 0, 0, 0, 0, time.UTC)},                             // vertex_ai-language-models
}

// builtinContextWindows is the max INPUT window per model, in tokens,
// straight from LiteLLM's max_input_tokens. Read it through
// BuiltinContextWindow. mast has no context-window consumer yet — the
// parent project's usage tracker prefers an exact hit here over a
// substring fallback, and a mast port would do the same: generated
// numbers for anything we ship a rate for, a fallback for operator
// ids that never appear in LiteLLM (long-context "-1m" suffixes,
// Vertex publication names).
//
// Note these are INPUT windows, not total: a model with a 1,048,576
// input cap may accept fewer once its max_output_tokens reservation is
// subtracted. Compaction thresholds are fractions of this number, so
// erring toward the input cap keeps the trigger conservative.
var builtinContextWindows = map[string]int{
	"claude-fable-5":                        1000000,
	"claude-fable-5-1":                      1000000,
	"claude-haiku-4-5":                      200000,
	"claude-haiku-4-5-20251001":             200000,
	"claude-mythos-5":                       1000000,
	"claude-mythos-preview":                 1000000,
	"claude-opus-4-5":                       200000,
	"claude-opus-4-5-20251101":              200000,
	"claude-opus-4-6":                       1000000,
	"claude-opus-4-6-20260205":              1000000,
	"claude-opus-4-7":                       1000000,
	"claude-opus-4-7-20260416":              1000000,
	"claude-opus-4-8":                       1000000,
	"claude-opus-5":                         1000000,
	"claude-sonnet-4-5":                     200000,
	"claude-sonnet-4-5-20250929":            200000,
	"claude-sonnet-4-6":                     1000000,
	"claude-sonnet-5":                       1000000,
	"gemini-2.5-flash":                      1048576,
	"gemini-2.5-flash-lite":                 1048576,
	"gemini-2.5-flash-lite-preview-09-2025": 1048576,
	"gemini-2.5-flash-preview-09-2025":      1048576,
	"gemini-2.5-pro":                        1048576,
	"gemini-3-flash-preview":                1048576,
	"gemini-3.1-flash-lite":                 1048576,
	"gemini-3.1-flash-lite-preview":         1048576,
	"gemini-3.1-pro-preview":                1048576,
	"gemini-3.1-pro-preview-customtools":    1048576,
	"gemini-3.5-flash":                      1048576,
	"gemini-3.5-flash-lite":                 1048576,
	"gemini-3.6-flash":                      1048576,
	"gemini-3.7-flash":                      1048576,
}

// Builtin returns a defensive copy of the compiled-in table. Used
// by tests + by tools that want to inspect what shipped (e.g. a
// future `/pricing list builtin` view).
//
// Bare model ids only. The backend-qualified rows are a separate table
// with a separate accessor, because the invariants differ: every entry
// here is a model mast will run, and so must carry a tier and a context
// window, while a qualified row is a price for a model already listed
// here and carries neither.
func Builtin() map[string]Rates {
	out := make(map[string]Rates, len(builtin))
	for k, v := range builtin {
		out[k] = v
	}
	return out
}

// BuiltinByBackend returns a defensive copy of the compiled-in
// (backend, model) table, keyed "<backend>/<model>". See LookupFor for
// the resolution order that consults it.
func BuiltinByBackend() map[string]Rates {
	out := make(map[string]Rates, len(builtinByBackend))
	for k, v := range builtinByBackend {
		out[k] = v
	}
	return out
}

// BuiltinContextWindow returns the compiled-in max input window for
// modelID and whether one is known. Keys are lowercase, matching the
// rest of this package's case-insensitive lookup contract; callers
// holding an operator-typed id should lower it first.
//
// Separate from Rates because a context window is a capability, not a
// price: operator pricing overrides (.agents/pricing.json, `/pricing set`)
// must not be able to move a model's window, and a model can be
// repriced without its window changing.
func BuiltinContextWindow(modelID string) (int, bool) {
	n, ok := builtinContextWindows[modelID]
	return n, ok
}

// BuiltinContextWindows returns a defensive copy of the whole window
// table, for tests and cross-table invariant checks.
func BuiltinContextWindows() map[string]int {
	out := make(map[string]int, len(builtinContextWindows))
	for k, v := range builtinContextWindows {
		out[k] = v
	}
	return out
}
