// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Originally derived from go-steer/core-agent@83ec0713ade7a5c05d72ad280039f336f561414b

// Code generated by dev/regen-builtin-pricing. DO NOT EDIT.
//
// Regenerated 2026-07-20 from https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json.
//
// To refresh: `go run ./dev/regen-builtin-pricing`
// Curate the allowlist in dev/regen-builtin-pricing/main.go.
//
// Issue #259 context: this file used to be hand-authored, drifted
// silently, and shipped rates that were off by 20-30x during the
// v2.7.0-dev.3 demo drive. The regen path is the mitigation — every
// entry carries an UpdatedAt so operators can spot stale entries via
// /pricing, and the whole file rebuilds from LiteLLM's authoritative
// catalog rather than accreting hand-edits.

package pricing

import "time"

var builtin = map[string]Rates{
	"claude-haiku-4-5":      {InputPerMTok: 1, CachedInputPerMTok: 0.1, OutputPerMTok: 5, UpdatedAt: time.Date(2026, 7, 20, 0, 0, 0, 0, time.UTC)},        // anthropic
	"claude-opus-4-7":       {InputPerMTok: 5, CachedInputPerMTok: 0.5, OutputPerMTok: 25, UpdatedAt: time.Date(2026, 7, 20, 0, 0, 0, 0, time.UTC)},       // anthropic
	"claude-opus-4-8":       {InputPerMTok: 5, CachedInputPerMTok: 0.5, OutputPerMTok: 25, UpdatedAt: time.Date(2026, 7, 20, 0, 0, 0, 0, time.UTC)},       // anthropic
	"claude-sonnet-5":       {InputPerMTok: 2, CachedInputPerMTok: 0.2, OutputPerMTok: 10, UpdatedAt: time.Date(2026, 7, 20, 0, 0, 0, 0, time.UTC)},       // anthropic
	"gemini-3.1-flash-lite": {InputPerMTok: 0.25, CachedInputPerMTok: 0.025, OutputPerMTok: 1.5, UpdatedAt: time.Date(2026, 7, 20, 0, 0, 0, 0, time.UTC)}, // vertex_ai-language-models
	"gemini-3.5-flash":      {InputPerMTok: 1.5, CachedInputPerMTok: 0.15, OutputPerMTok: 9, UpdatedAt: time.Date(2026, 7, 20, 0, 0, 0, 0, time.UTC)},     // vertex_ai-language-models
}

// Builtin returns a defensive copy of the compiled-in table. Used
// by tests + by tools that want to inspect what shipped (e.g. a
// future `/pricing list builtin` view).
func Builtin() map[string]Rates {
	out := make(map[string]Rates, len(builtin))
	for k, v := range builtin {
		out[k] = v
	}
	return out
}
